default_config:
homeassistant:
  latitude: !secret lat
  longitude: !secret lon

recorder:
  db_url: !secret mariadb_path
  auto_purge: true
  purge_keep_days: 14
  commit_interval: 0

frontend:
  themes: !include_dir_merge_named themes

tts:
  - platform: google_translate

http:
  server_port: !secret http_port
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 6
  cors_allowed_origins:
    - https://google.com
    - https://www.google.com
    - https://home-assistant.io
    - https://www.home-assistant.io
    - https://nabucasa.com
    - https://www.nabucasa.com
    - https://googleapis.com
    - https://ajax.googleapis.com
    - https://www.googleapis.com
    - https://gstatic.com
    - https://www.gstatic.com

cloudflare:
  email: !secret email_address
  api_key: !secret cloudflare_global
  zone: leviathan.network
  records:
    - leviathan.network

notify:
  - platform: html5
    name: FireNotifier
    vapid_pub_key: !secret firebase_public_key
    vapid_prv_key: !secret firebase_private_key
    vapid_email: !secret firebase_acct

input_select:
  levi:
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
  maria:
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away

input_number:
  occupancy:
    initial: 2
    min: 0
    max: 50
    step: 1
    mode: box

hacs:
  token: dc899bf5b7a27354147439820318ffe6546cc8d5
  theme: true
  appdaemon: true
  netdaemon: true
  python_script: true

auto_backup:
  auto_purge: true
  backup_timeout: 1800

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
